### ISSUE TITLE
Docker Instructions not clear - Different issues

### ISSUE THREAD

**Issue by cesalo** [chrisvel/wreeto_official#13]
Sorry if these are obvious questions but I can't run this image after several attempts.
I tried at the beginning when there was no a docker image so I did a clone and then a build.
After your last update I did the following:

- Remove all the docker instances running from before.
- Remove all the files from the git clone and build command.
- Run: docker pull docker.io/chrisvel/wreeto
- Copy the docker-compose.yml
- Run: docker-compose up -d

This complained about the file .env so I copy the .env and run again: docker-compose up -d
This complained about the file ./docker-entrypoint.sh

What files do I need to copy before running: docker-compose up -d.

I'm a bit confused any help will be appreciated it.
I think if possible clear instructions will help testing this app, specially for the ppl not that familiar with docker-compose (like me :) ).

**Comment by chrisvel** [comment]
No problem, I am more than happy to help. Some things seem clear to me but I totally understand that may confuse others. 

Best thing to do is to clone the repository and just run `docker-compose up`. There is nothing else necessary to be done. 

If you decide to just copy the `docker-compose.yml` locally and try to run the app, you need the `.env` and `docker-entrypoint.sh`. 

You can always run `docker-compose pull` to get latest  images. 

I will definitely update the README as soon as possible. What is the problem you're having right now with successfully running the app?

**Comment by cesalo** [comment]
Thanks @chrisvel - Now I finally got the app up and running. I needed to do the clone again :).
Now I'm having issues logging in - When I introduce the user/pass from the readme it fails and I see this msg in the logs:

```
Started POST "/users/sign_in" for 192.168.XXX.XXX at 2020-05-14 15:50:35 +0000
Cannot render console from 192.168.XXX.XXX! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"3olFyQ7yR3m5NnSn9/VVAnwT4D3O+AIA023IJRWepY7tJvOdSBg3D3X+DrIfWROVWMbAraiKeTv9n0aTB1aVGg==", "user"=>{"email"=>"user@email.com", "password"=>"[FILTERED]", "remember_me"=>"1"}, "button"=>""}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "user@email.com"], ["LIMIT", 1]]
Completed 401 Unauthorized in 2ms (ActiveRecord: 0.4ms)


Processing by Devise::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"3olFyQ7yR3m5NnSn9/VVAnwT4D3O+AIA023IJRWepY7tJvOdSBg3D3X+DrIfWROVWMbAraiKeTv9n0aTB1aVGg==", "user"=>{"email"=>"user@email.com", "password"=>"[FILTERED]", "remember_me"=>"1"}, "button"=>""}
  Rendering users/sessions/new.html.erb within layouts/empty
  Rendered users/sessions/new.html.erb within layouts/empty (1.7ms)
  Rendered layouts/_messages.html.erb (0.4ms)
  Rendered layouts/_footer.html.erb (0.1ms)
Completed 200 OK in 101ms (Views: 14.4ms | ActiveRecord: 0.0ms)
```

**Comment by chrisvel** [comment]
Something must have gone wrong in a previous migration. 

Can you please try `docker-compose run app bundle exec rake db:drop db:migrate db:setup`?

This command actually re-initialises the database for the app. You should see this last message:
```
=> Creating default user [user@email.com:password]
```

**Comment by cesalo** [comment]
Nice, thanks that worked like a charm. Last question, now i see the following docker instances running:

```
docker ps -a | grep wreeto
b0f472535f41        chrisvel/wreeto:latest                       "./docker-entrypoi..."   52 seconds ago      Exited (0) 43 seconds ago                                                                                              wreeto_official_app_run_1
38c3a6d7a181        chrisvel/wreeto:latest                       "./docker-entrypoi..."   17 minutes ago      Up 17 minutes               0.0.0.0:8383->8383/tcp                                                                     wreeto_official_app_1
9c2454f60292        redis:5.0.7                                  "docker-entrypoint..."   17 minutes ago      Up 17 minutes               6379/tcp                                                                                   wreeto_official_redis_1
e08962b9425f        postgres:11                                  "docker-entrypoint..."   17 minutes ago      Up 17 minutes               5432/tcp                                                                                   wreeto_official_postgres_1
```
Not sure about the difference between  wreeto_official_app_run_1 and wreeto_official_app_1 .. maybe I made some kind of mistake (??). I could login so I assume is safe to remove wreeto_official_app_run_1. Can you please confirm?

**Comment by chrisvel** [comment]
Yes, the `run` one was necessary for the command you executed. You can remove it.

**Comment by cesalo** [comment]
Thanks, sorry last question: If you publish an update the steps would be:
reclone: git clone git://github.com/chrisvel/wreeto_official.git
docker pull
docker-compose -d
or a different approach?
