### ISSUE TITLE
bundle exec rake db:setup does not work

### ISSUE THREAD

**Issue by hugo-blomdahl** [chrisvel/wreeto_official#2]
After a while while running `bundle exec rake db:setup` the entire terminal fils up with endless amounts of `Category Exists (0.1ms)  SELECT  1 AS one FROM "categories" WHERE "categories"."slug" = $1 AND "categories"."user_id" = $2 LIMIT $3  [["slug", "projects"], ["user_id", 1], ["LIMIT", 1]]` messages. The output right before this happens is <br /> `(194.1ms)  COMMIT`
  `User Load (0.7ms)`  
`SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
   (0.1ms)  BEGIN`

**Comment by chrisvel** [comment]
Please pull and re-run. Issue fixed. 
Thank you for this.
