### ISSUE TITLE
Errors with docker-compose up

### ISSUE THREAD

**Issue by AbramsM1A2** [chrisvel/wreeto_official#25]
Hi, when i do docker-compose up the following error appears:
`
ERROR: for cef0c55655ea_wreeto_official_app_1  Cannot start service app: driver failed programming external connectivity on endpoint cef0c55655ea_wreeto_official_app_1 (263653c3c99ecb76fa7b2b89f783852f205d155aa591f18fca3b99a5d5de4df0):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8383 -j DNAT --to-destination 172.18.0.4:8383 ! -i br-f4f3e3548555: iptables v1.8.2 (nf_tables): unknown option "--dport"
Try iptables -h' or 'iptables --help' for more information.
 (exit status 2))`
`
ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint cef0c55655ea_wreeto_official_app_1 (263653c3c99ecb76fa7b2b89f783852f205d155aa591f18fca3b99a5d5de4df0):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8383 -j DNAT --to-destination 172.18.0.4:8383 ! -i br-f4f3e3548555: iptables v1.8.2 (nf_tables): unknown option "--dport"
Try iptables -h' or 'iptables --help' for more information.
 (exit status 2))
ERROR: Encountered errors while bringing up the project`
Im a bit rookie with linux and docker, so i dont know where to look in order to solve this. Any help its appreciated.
Im running this on my raspberry pi 4 with raspbian

**Comment by chrisvel** [comment]
This is not related to the project but docker or/and raspbian. Have tried to ask for help on a raspbian or docker channel in reddit? 

Also, I am not sure wreeto will work in an ARM device (for now) as it will require a separate image build for that.

**Comment by AbramsM1A2** [comment]
Oh i didnt count with that, i will try to install manually and see what happens. Thank you and have a nice day

**Comment by chrisvel** [comment]
no problem @AbramsM1A2, cheers !
