### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by AbramsM1A2** [chrisvel/wreeto_official#27]
When following the documentation the .env file where you put your ip instead of localhost is not working. When i  launch _bundle exex rails s_ always uses localhost. 
My goal is running this app on my ip so i can use it with any device, but i dont know how to do it, since the .env file doesnt work.

Help is apreciated, thanks.

**Comment by chrisvel** [comment]
I'm sorry for the late reply. 
The IP address in the `.env` file will surely work If the app is installed manually and foreman is used. 

If docker is going to be used, it's necessary to setup the appropriate network depending on your system and its configuration. 

If you are going to start the rails server manually, you need to pass the binding IP and/or the port: 

```
bundle exec rails s -b <ip_address> -p <port>
# For example, bundle exec rails s -b 192.168.1.2 -p 1234
```

Does it make sense ?

**Comment by AbramsM1A2** [comment]
Oh i see..., now is working. There is a thing i dont understand in this whole process, in the .env file i specify the _host name_ with ip _192.168.1.2_ and then you call _bundle exec rails s -b 192.168.1.2_ , isn't it redundant?

**Comment by chrisvel** [comment]
Yes and no. It depends on how are you going to use the app. Starting the rails server manually overrides the `.env` vars and I guess that's not going to be used by the majority of people except from those who want to experiment on a development level.
