### ISSUE TITLE
shebangs inside code brackets will make the note unreadable

### ISSUE THREAD

**Issue by Ch0wW** [chrisvel/wreeto_official#45]
Steps to reproduce : 

- Create a note
- Type the following : 
```

```#!/bin/bash

echo "test"```
```

![image](https://user-images.githubusercontent.com/2938006/93781581-cfe56f00-fc29-11ea-9593-7141917edab5.png)

When saving, the note will be unreachable.

![image](https://user-images.githubusercontent.com/2938006/93781551-c825ca80-fc29-11ea-9c75-2d65c49cd413.png)

Also, no logs is present reporting this issue after I did that.

**Comment by chrisvel** [comment]
Issue fixed in `master` and `v2.5.7`.
