### ISSUE TITLE
Omit `WREETO_PORT` for behind the reverse proxy setup

### ISSUE THREAD

**Issue by m0nhawk** [chrisvel/wreeto_official#52]
I really liked Wreeto, the only thing I'm having issue is `WREETO_PORT`.

The logo points to `http://my.domain:8383/`, and because I'm running everything behind Traefik, I'd like it to point to `https://my.domain/` – with https and without the port part.

But I can't figure out how to do that.

As I understand, it's not supported from [here](https://github.com/chrisvel/wreeto_official/blob/master/lib/utils/base_config.rb#L7). If I understand correctly, it can be patched like this:

```
module Utils 
  module BaseConfig 

    def base_url
      host = ENV["WREETO_HOST"] || 'localhost'
      port = ENV["WREETO_PORT"] || 8383
      behind_proxy = ENV["BEHIND_PROXY"] || 'no'
      protocol = ENV["PROTOCOL"] || 'http'
      if behind_proxy == 'yes'
        "#{protocol}://#{host}"
      else
        "#{protocol}://#{host}:#{port}"
      end
    end
  end 
end
```

**Comment by chrisvel** [comment]
I am sorry for the late reply, I've been very busy with the cloud version of **wreeto** for the last few months. 
I will apply the change ASAP.
