### ISSUE TITLE
cannot create user

### ISSUE THREAD

**Issue by airdogvan** [chrisvel/wreeto_official#6]
tried running (after having run docker-compose up 1 time and then stopping it)
docker-compose run app bundle exec rails c and then
User.create!({firstname: 'John', lastname: 'Murdock', email: 'user@email.com', password: 'password', confirmed_at: DateTime.now})
but nothing happened after typing exit
just stayed there no reaction after long time (10 minutes)

Tried to create user on web interface and was told "invalid server key" or something similar.

**Comment by chrisvel** [comment]
@airdogvan please run `docker-compose pull` to get the latest images, some bugs have been fixed. You should be able to run the command you described and exit. 

For a clean database setup you can run `docker-compose run app bundle exec rake db:drop db:migrate db:setup` and then try to log in. 

You won't be able to register for a new user via the web page for now, as it requires some additional setup. I am working on simplifying this.

**Comment by airdogvan** [comment]
thank you, did a pull (no change in images) restarted with docker-compose run app bundle exec rails c
and not sure why but this time it worked, gave me a prompt that allowed me to enter new user, exited and restarted with up and worked fine.  Not sure what didn't work first time I tried.
Thank you again.  Will certainly give your app a spin and thanks so much for making it available!

**Comment by chrisvel** [comment]
@airdogvan thanks a lot, I hope you like it.
