### ISSUE TITLE
recaptcha not working when running using docker-compose

### ISSUE THREAD

**Issue by henkisdabro** [chrisvel/wreeto_official#7]
out of the box, running `docker-compose up` with the provided basic template renders a signup page with a broken recaptcha.

**Comment by chrisvel** [comment]
This is known - it's a leftover bug from the cloud to open source project transition. I'll fix it the soonest possible.

**Comment by chrisvel** [comment]
Signup page and re-captcha have been disabled for now. New accounts must be created through console as per README instructions, only temporarily, until I add a user management page for this purpose. Resolving for now.
